[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "26378631e0660d8994314119afa95ffefa09ca6b", features = ["web"] }
