[workspace]
members = ["gen"]

[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
data = { path = "./data" }

dioxus = "0.4"
dioxus-web = "0.4"

web-sys = { version = "0.3", features = ["Window", "History", "Location"] }
gloo-utils = "0.2"
gloo-storage = "0.3"

log = "0.4"
wasm-logger = "0.2"

reqwest = "0.11"

anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
