[workspace]
members = ["gen", "sandbox"]

[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
data = { path = "./data" }

dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "87dc409837f1294952a2552068db99dc17d701db", features = ["router", "web"] }

wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window", "History", "Location", "HtmlDialogElement"] }
gloo-utils = "0.2"
gloo-storage = "0.3"

log = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-web = "0.1"

reqwest = "0.11"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

indicium = { git = "https://github.com/atty303/indicium.git", rev = "a3c8c168e0c4f9167612b80eda194b2a179e5338" }
getrandom = { version = "0.2", features = ["js"] }

anyhow = "1.0"
ref-cast = "1.0"
