[package]
name = "web"
version = "0.1.0"

[dependencies]
app = { workspace = true }
dioxus = { workspace = true }

tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-web = "0.1"
