[package]
name = "auth0-spa"
edition = "2021"
version.workspace = true

[dependencies]
dioxus = { workspace = true }
futures-util = "0.3"
futures-channel = "0.3"
serde = { version = "1.0.196", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
typed-builder = "0.18"
web-sys = "0.3"
tracing = "0.1"
