[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
data = { workspace = true }

dioxus-headlessui = { git = "https://github.com/atty303/dioxus-headlessui.git" }

dioxus = { workspace = true, features = ["router", "web"] }
dioxus-signals = { workspace = true, features = ["serde"] }

wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "History", "Location", "HtmlDialogElement", "DomRect"] }
gloo-utils = "0.2"
gloo-storage = "0.3"

tracing = "0.1"

reqwest = "0.11"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.1"
serde-wasm-bindgen = "0.6"
base64 = "0.21"

indicium = { git = "https://github.com/atty303/indicium.git", rev = "a3c8c168e0c4f9167612b80eda194b2a179e5338" }
getrandom = { version = "0.2", features = ["js"] }

anyhow = "1.0"
ref-cast = "1.0"

markdown-it = "0.6"
futures-channel = "0.3.30"
futures-util = "0.3.30"
typed-builder = "0.18"
