[package]
name = "bb2b-worker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
app = { workspace = true }
dioxus = { workspace = true }
dioxus-fullstack = { workspace = true, features = ["server", "cloudflare-workers"]  }

#axum = { version = "0.7", default-features = false }
#tokio = { version = "1.36", default-features = false, features = [] }

worker = "0.0.18"
#axum-cloudflare-adapter = "0.7"
